=== rivm-syso/intorods/schemas/pipeline_output_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "collection": {
      "type": "string"
    },
    "checksum_format": {
      "type": "string",
      "enum": ["sha256"]
    },
    "version": {
      "type": "integer"
    },
    "checksum_encoding": {
      "type": "string",
      "enum": [ "hex", "base64" ]
    },
    "objects": {
      "type": "array",
      "items": {
         "type": "object",
         "properties": {
            "path": {
              "type": "string"
            },
            "checksum": {
              "type": "string"
            },
            "create_time": {
              "type": "integer"
            },
            "type": {
              "type": "string",
              "enum": [ "dataobject", "collection" ]
            },
            "metadata": {
              "type": "array",
              "items": {
                 "type": "object",
                 "properties": {
                    "units": {
                      "type": "string"
                    },
                    "attr": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "units",
                    "attr",
                    "value"
                  ]
              }  
            }
          },
         "required": [
            "path",
            "checksum",
            "type"
          ]
      }
    }
  },
  "required": [
      "collection",
      "checksum_format",
      "version",
      "checksum_encoding",
      "objects"
  ]  
}

=== rivm-syso/intorods/test/test_generic_json_checksum/csf.json
{
   "collection": "test",
   "checksum_format": "sha256",
   "version": 1,
   "checksum_encoding": "hex",
   "objects": [
      {
         "path": "subdir_b/c.txt",
         "checksum": "6f2de4a01270ba6d72d0b60d4ee5d8c67999d3dbcedeb95f9bab1826446b432f",
         "type": "dataobject"
      },
      {
         "path": "output_wrong",
         "checksum": "0d5cbdc1cd85f21602b87ad5ecff5b3aab705f67758ddcf0c47be68d11c480d1",
         "type": "dataobject"
      },
      {
         "path": "a.txt",
         "checksum": "823237c5460d242b9189d8ca7aa5d5becd3ceb5e8a8c158766275bd77f4ccc3c",
         "type": "dataobject"
      },
      {
         "path": "b.txt",
         "checksum": "a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447",
         "type": "dataobject"
      },
      {
         "path": "output_checksum",
         "checksum": "afb09b24fd9edcd07cf37bf995cb1fb802596ec29ef101845587cfa6099c553c",
         "type": "dataobject"
      }
   ]
}
